### ISSUE TITLE
Can´t install the package

### ISSUE THREAD

**Issue by adsepulv** [glenmcgee/bsmim2#7]
Hi!
I tried to install the package in macOS Sonoma 14.3.1 on a MacBook Air M1 using R-studio, but after many tries, I failed.
Can you help, please??

Alejandro Sepúlveda

**Comment by glenmcgee** [comment]
What errors are you getting?
I was able to install via:

devtools::install_github("glenmcgee/bsmim2",force=TRUE)

**Comment by adsepulv** [comment]
When I install on Mac Air M1, Sonoma 14.5, the following message appears, which I have attached two images.

<img width="1113" alt="Captura de pantalla 2024-06-03 a la(s) 2 13 16 p  m" src="https://github.com/glenmcgee/bsmim2/assets/63556990/fd7342d1-1b40-4c77-bb3c-48e5779f4dfc">

<img width="1112" alt="Captura de pantalla 2024-06-03 a la(s) 2 10 05 p  m" src="https://github.com/glenmcgee/bsmim2/assets/63556990/9aa7c3ee-f36e-4a1b-ad65-841fdcf27612">

I also tried to install it using R Studio Cloud, and I got another message, which I also attached.
<img width="1112" alt="Captura de pantalla 2024-06-03 a la(s) 2 10 05 p  m" src="https://github.com/glenmcgee/bsmim2/assets/63556990/5cb3bc4d-1eb0-413d-8827-84fa6436cfc4">

**Comment by AnderWilson** [comment]
Will you please try installing the package from the dev branch?

**Comment by adsepulv** [comment]
I tried. Now this problem appears:

> ld: warning: search path '/opt/gfortran/lib/gcc/aarch64-apple-darwin20.0/12.2.0' not found
> ld: warning: search path '/opt/gfortran/lib' not found
> ld: library 'gfortran' not found
> clang: error: linker command failed with exit code 1 (use -v to see invocation)
> make: *** [bsmim2.so] Error 1
> ERROR: compilation failed for package ‘bsmim2’
> * removing ‘/Library/Frameworks/R.framework/Versions/4.4-arm64/Resources/library/bsmim2’
> 
> Exited with status 1.

I have tried to solve the problem with that library, but I have not been able to. Can you help me with that?

**Comment by AnderWilson** [comment]
Do you have the latest Xcode and gfortran installed? See this: https://cran.r-project.org/bin/macosx/tools/

**Comment by adsepulv** [comment]
Thank you very much for your help. Finally, I was able to install it.
